config/routes.rb
FriendSeeker::Application.routes.draw do
  get "profile/show"
  match "profile/show" => 'profile#show'
  devise_for :authens

  get "home/index"
  root :to => 'home#index' 

   

end

app/models/authen.rb
class Authen < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me , :username , :country
  # attr_accessible :title, :body
  validates_presence_of :username , :country
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # attr_accessible :title, :body
 has_attached_file :photo, :styles => {:small => "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/index.html.erb
<h1><center>Welcome To Friendseeker</center></h1><br>
<% if authen_signed_in?%>
<center><%= link_to "Profile",profile_show_path%></center>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendseeker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: #add8e6;" >
 <div id="authen_nav">
   <% if authen_signed_in? %>

   <div align="right"> Signed in as: <%=  current_authen.username  %>&nbsp; <br>
   <%= link_to "SIGN OUT", destroy_authen_session_path, :method => :delete %></div>
    <% else %>
    <div align="right"><%= link_to "SIGN IN",new_authen_session_path %>&nbsp; OR &nbsp;
    <%= link_to "SIGN UP", new_authen_registration_path %></div>
   <%end%>
   </div>
<%= yield %>

</body>
</html>